# Generated by Django 5.1.15 on 2026-09-07 14:45

import django.db.models.deletion
import papers.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('co_authors', models.CharField(blank=True, max_length=255)),
                ('current_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_COORD', 'Pending Coordinator Triage'), ('REJECTED_INITIAL', 'Rejected at Triage'), ('PENDING_ADVISOR', 'Under Peer Review'), ('ADVISOR_COMMENTED', 'Reviews Submitted (Awaiting Consolidation)'), ('REVISION_REQUIRED', 'Revision Required'), ('ADVISOR_APPROVED', 'Reviewers Approved'), ('PUBLISHED', 'Published (Archived Lock)')], default='DRAFT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'papers_paper',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Clinical justification for requesting full-text reading access.')),
                ('duration_days', models.PositiveIntegerField(choices=[(7, '7 Days Pass (Urgent Consultation)'), (14, '14 Days Pass (Departmental Research)'), (30, '30 Days Pass (Fellowship & Study)')], default=7)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('coordinator_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_access_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_access_requests', to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='papers.paper')),
            ],
            options={
                'db_table': 'papers_accessrequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('pdf_file', models.FileField(upload_to=papers.models.protected_paper_path)),
                ('summary_notes', models.TextField(blank=True, help_text="Author's notes regarding this submission round.")),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='papers.paper')),
            ],
            options={
                'db_table': 'papers_paperround',
                'ordering': ['round_number'],
                'unique_together': {('paper', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='CoordinatorLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consolidated_comment', models.TextField(help_text='Consolidated synthesis and revision directives')),
                ('decision', models.CharField(choices=[('REVISION_REQUIRED', 'Require Author Revisions'), ('APPROVED', 'Approve for Publication')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_letters', to=settings.AUTH_USER_MODEL)),
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_letter', to='papers.paperround')),
            ],
            options={
                'db_table': 'papers_coordinatorletter',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='papers.paperround')),
            ],
            options={
                'db_table': 'papers_reviewassignment',
                'ordering': ['-assigned_at'],
                'unique_together': {('round', 'reviewer')},
            },
        ),
        migrations.CreateModel(
            name='ReviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_comment', models.TextField(help_text='เค้าโครง: Structure & Methodology critique')),
                ('intro_comment', models.TextField(help_text='บทนำ: Introduction & Literature critique')),
                ('expansion_comment', models.TextField(help_text='บทขยาย: Results, Data & Discussion critique')),
                ('decision', models.CharField(choices=[('REVISION_NEEDED', 'Request Revisions'), ('APPROVED', 'Approve as Final')], default='REVISION_NEEDED', max_length=20)),
                ('annotated_pdf', models.FileField(blank=True, null=True, upload_to=papers.models.protected_review_path)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='papers.reviewassignment')),
            ],
            options={
                'db_table': 'papers_reviewfeedback',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
