# Generated by Django 5.1.15 on 2026-09-07 15:00

import django.core.files.storage
import papers.models
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperround',
            name='pdf_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/nuts/NasHospitalSystem/protected_media')), upload_to=papers.models.protected_paper_path),
        ),
        migrations.AlterField(
            model_name='reviewfeedback',
            name='annotated_pdf',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/nuts/NasHospitalSystem/protected_media')), upload_to=papers.models.protected_review_path),
        ),
    ]
