# Generated by Django 5.1.15 on 2026-09-07 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_alter_paperround_pdf_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='retraction_reason',
            field=models.TextField(blank=True, help_text='Clinical justification for post-publication recall.'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='current_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_COORD', 'Pending Coordinator Triage'), ('REJECTED_INITIAL', 'Rejected at Triage'), ('PENDING_ADVISOR', 'Under Peer Review'), ('ADVISOR_COMMENTED', 'Reviews Submitted (Awaiting Consolidation)'), ('REVISION_REQUIRED', 'Revision Required'), ('ADVISOR_APPROVED', 'Reviewers Approved'), ('PUBLISHED', 'Published (Archived Lock)'), ('RETRACTED_FOR_REVISION', 'Retracted for Revision')], default='DRAFT', max_length=30),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('PAPER_ASSIGNED', 'Paper Assigned for Review'), ('REVIEW_SUBMITTED', 'Review Critique Submitted'), ('DIRECTIVE_ISSUED', 'Revision Directive Issued'), ('PAPER_RETRACTED', 'Paper Recalled for Revision'), ('ACCESS_GRANTED', 'Access Pass Granted'), ('REVISION_SUBMITTED', 'Revision Round Submitted'), ('SYSTEM', 'System Alert')], default='SYSTEM', max_length=30)),
                ('message', models.CharField(max_length=255)),
                ('target_url', models.CharField(default='#', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='papers.paper')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'papers_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
