# Generated by Django 5.1.15 on 2026-09-08 09:37

import papers.models
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_paper_retraction_reason_alter_paper_current_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='paper',
            name='current_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_COORD', 'Pending Coordinator Triage'), ('REJECTED_INITIAL', 'Rejected at Triage'), ('PENDING_ADVISOR', 'Under Peer Review'), ('ADVISOR_COMMENTED', 'Reviews Submitted (Awaiting Consolidation)'), ('REVISION_REQUIRED', 'Revision Required'), ('ADVISOR_APPROVED', 'Reviewers Approved'), ('PUBLISHED', 'Published (Archived Lock)'), ('RETRACTED_FOR_REVISION', 'Retracted for Revision')], db_index=True, default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='paperround',
            name='pdf_file',
            field=models.FileField(storage=papers.models.EncryptedFileSystemStorage(location=pathlib.PurePosixPath('/home/nuts/NasHospitalSystem/protected_media')), upload_to=papers.models.protected_paper_path),
        ),
        migrations.AlterField(
            model_name='reviewfeedback',
            name='annotated_pdf',
            field=models.FileField(blank=True, null=True, storage=papers.models.EncryptedFileSystemStorage(location=pathlib.PurePosixPath('/home/nuts/NasHospitalSystem/protected_media')), upload_to=papers.models.protected_review_path),
        ),
    ]
