# Generated by Django 5.1.15 on 2026-09-07 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN_SUCCESS', 'User Login'), ('LOGIN_2FA', '2FA Verification Success'), ('LOGOUT', 'User Logout'), ('STREAM_PDF', 'Protected PDF Streamed'), ('SUBMIT_PAPER', 'Manuscript Submitted'), ('ASSIGN_REVIEWER', 'Reviewer Assigned'), ('SUBMIT_REVIEW', 'Critique Submitted'), ('DISPATCH_LETTER', 'Coordinator Letter Dispatched'), ('PUBLISH_PAPER', 'Paper Published & Locked'), ('RETRACT_PAPER', 'Paper Recalled for Revision'), ('REQUEST_ACCESS', 'Access Pass Requested'), ('GRANT_ACCESS', 'Access Pass Granted'), ('DENY_ACCESS', 'Access Pass Denied'), ('RESET_2FA', '2FA Reset by Administrator'), ('USER_CREATE', 'User Created'), ('USER_UPDATE', 'User Updated'), ('USER_TOGGLE_ACTIVE', 'User Active Status Toggled')], max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_auditlog',
                'ordering': ['-timestamp'],
            },
        ),
    ]
