# Generated by Django 5.1.15 on 2026-09-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'User Login'), ('LOGIN_FAILURE', 'Failed Login Attempt'), ('LOGIN_2FA', '2FA Verification Success'), ('LOGOUT', 'User Logout'), ('STREAM_PDF', 'Protected PDF Streamed'), ('SUBMIT_PAPER', 'Manuscript Submitted'), ('ASSIGN_REVIEWER', 'Reviewer Assigned'), ('SUBMIT_REVIEW', 'Critique Submitted'), ('DISPATCH_LETTER', 'Coordinator Letter Dispatched'), ('PUBLISH_PAPER', 'Paper Published & Locked'), ('RETRACT_PAPER', 'Paper Recalled for Revision'), ('REQUEST_ACCESS', 'Access Pass Requested'), ('GRANT_ACCESS', 'Access Pass Granted'), ('DENY_ACCESS', 'Access Pass Denied'), ('RESET_2FA', '2FA Reset by Administrator'), ('USER_CREATE', 'User Created'), ('USER_UPDATE', 'User Updated'), ('USER_TOGGLE_ACTIVE', 'User Active Status Toggled')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DOCTOR', 'Doctor (Author & Reviewer)'), ('COORDINATOR', 'Research Coordinator'), ('STAFF_VIEWER', 'Staff Clinician / Viewer'), ('ADMIN', 'System Administrator')], db_index=True, default='DOCTOR', help_text='Unified Doctor role allows both authoring and reviewing peer papers.', max_length=20),
        ),
    ]
